### ISSUE TITLE
Issue generating world

### ISSUE THREAD

**Issue by BodyshotzVG** [kitskub/bSpace#69]
Well, the title pretty much explains it. But, lemme show a picture of the console and my config.

http://puu.sh/8Ny6
Console

http://puu.sh/8Nyb
Configuration file

I do have multiverse enabled, because I have and use multiple worlds such as a freebuild, survival, etc. 

It would really be appreciated if I could get some help on this matter. Thanks!

EDIT: You need to make it Multiverse compatible, as I need multiple worlds. The BananaSpace works without Multiverse only, which really sucks.

**Comment by kitskub** [comment]
Can you post a pastebin link to both your config files?

**Comment by iffa** [comment]
If you're going to use Multiverse to create space worlds, I'd suggest you use a build of v2

**Comment by kitskub** [comment]
At this point,I would say it is mostly stable, so yeah, use v2.

**Comment by kitskub** [comment]
And that error that you got, it is a configuration file error. It has nothing to do with bSpace. It is because of a bad config file. Paste your config file into  this:http://yaml-online-parser.appspot.com/ correct the errors it gives you, and it should be fine. Or, if you want post the whole thing and I'll find the error and correct it for you.
